

if(NOT DEFINED CMUT_COLOR_TEST_CONSOLE)

    if(CMUT__MESSAGE__USE_COLOR)
        set(CMUT_COLOR_TEST_CONSOLE 1)
    else()
        set(CMUT_COLOR_TEST_CONSOLE 0)
    endif()

endif()



if(CMUT_COLOR_TEST_CONSOLE)
  string(ASCII 27 Esc)
  set(cmut_color_message_ColorReset "${Esc}[m")
  set(cmut_color_message_ColorBold  "${Esc}[1m")
  set(cmut_color_message_Red         "${Esc}[31m")
  set(cmut_color_message_Green       "${Esc}[32m")
  set(cmut_color_message_Yellow      "${Esc}[33m")
  set(cmut_color_message_Blue        "${Esc}[34m")
  set(cmut_color_message_Magenta     "${Esc}[35m")
  set(cmut_color_message_Cyan        "${Esc}[36m")
  set(cmut_color_message_White       "${Esc}[37m")
  set(cmut_color_message_BoldRed     "${Esc}[1;31m")
  set(cmut_color_message_BoldGreen   "${Esc}[1;32m")
  set(cmut_color_message_BoldYellow  "${Esc}[1;33m")
  set(cmut_color_message_BoldBlue    "${Esc}[1;34m")
  set(cmut_color_message_BoldMagenta "${Esc}[1;35m")
  set(cmut_color_message_BoldCyan    "${Esc}[1;36m")
  set(cmut_color_message_BoldWhite   "${Esc}[1;37m")
endif()


function(cmut_color_message)
  if (ARGC EQUAL 0)
    message("")
  else()
    list(GET ARGV 0 MessageType)
    if(MessageType STREQUAL FATAL_ERROR OR MessageType STREQUAL SEND_ERROR)
      list(REMOVE_AT ARGV 0)
      message(${MessageType} "${BoldRed}${ARGV}${ColourReset}")
    elseif(MessageType STREQUAL WARNING)
      list(REMOVE_AT ARGV 0)
      message(${MessageType} "${BoldYellow}${ARGV}${ColourReset}")
    elseif(MessageType STREQUAL AUTHOR_WARNING)
      list(REMOVE_AT ARGV 0)
      message(${MessageType} "${BoldCyan}${ARGV}${ColourReset}")
    elseif(MessageType STREQUAL STATUS)
      list(REMOVE_AT ARGV 0)
      message(${MessageType} "${Green}${ARGV}${ColourReset}")
    else()
      message("${ARGV}")
    endif()
  endif()
endfunction()
