
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__chmod.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__find_program.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__fixup_dylib.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__get_build_time.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__get_num_colors_to_screen.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__header_guard.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__increment.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__is_running_in_terminal.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__parse_arguments.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__parse_version.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/utils/cmut__utils__set_version.cmake")
