
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__add_dependencies.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__default_build_type.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__default_cxx_standard.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__log_project.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_build_documentation.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_build_examples.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_build_shared_libs.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_ccache.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_clang_tidy.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_cppcheck.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_developer_mode.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_include_what_you_use.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__option_no_autodetect.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__print_info.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/config/cmut__config__resolve_install_prefix.cmake")
