


# define CMUT_WARNING_FLAGS

set(__CMUT_WARNING_GNU_COMPAT_COMPILER "-W -Wall")



if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    set(CMUT_WARNING_FLAGS /W4)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    set(CMUT_WARNING_FLAGS __CMUT_WARNING_GNU_COMPAT_COMPILER)
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    set(CMUT_WARNING_FLAGS __CMUT_WARNING_GNU_COMPAT_COMPILER)
endif()

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${__CMUT_WARNING_GNU_COMPAT_COMPILER}")