include_guard(GLOBAL)

include( "${CMAKE_CURRENT_LIST_DIR}/log/dev.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/log/debug.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/log/error.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/log/fatal.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/log/function_name_to_scope_name.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/log/init.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/log/info.cmake" )
include( "${CMAKE_CURRENT_LIST_DIR}/log/warn.cmake" )
